/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food.Regis;
import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BankSE
 */
public class AddMember extends javax.swing.JFrame {
    

Connection connect = null;

Statement s = null;


    // Model for Table

DefaultTableModel model;



    /**
     * Creates new form Form
     */
    public AddMember() {
      
        initComponents();
        reload();
        
        
        



    }

    
    
    /*************************************method delete*************************************/
    
   






/***************************************************************************************/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        de = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tf1.setEditable(false);
        tf1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf1.setDragEnabled(true);
        tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf1MouseClicked(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("รหัสสมาชก");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ชื่อ-นามสกุล");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ที่อยู่");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("เบอร์โทร");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(tf2)
                    .addComponent(tf3)
                    .addComponent(tf4))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        add.setText("เพิ่มสมาชิก");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        de.setText("ลบ");
        de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deActionPerformed(evt);
            }
        });

        jButton3.setText("แก้ไข");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("เคลียร์ฟอร์ม");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "รหัสสมาชิก", "ชื่อ-นามสกุล", "ที่อยู่", "เบอร์โทร"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        tb.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tbVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(tb);
        if (tb.getColumnModel().getColumnCount() > 0) {
            tb.getColumnModel().getColumn(0).setResizable(false);
            tb.getColumnModel().getColumn(1).setResizable(false);
            tb.getColumnModel().getColumn(2).setResizable(false);
            tb.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("สมัครสมาชิก");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(de, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(de, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/************************* ShowTable ***************************************/
    public void reload(){
       
// Clear table

tb.setModel(new DefaultTableModel());

// Model for Table

model = (DefaultTableModel) tb.getModel();

model.addColumn("รหัสสมาชก");

model.addColumn("ชื่อ-นามสกุล");

model.addColumn("ที่อยู่");

model.addColumn("เบอร์โทร");

  
    try {
       

Class.forName("com.mysql.jdbc.Driver");


connect =  DriverManager.getConnection("jdbc:mysql://localhost:3306/rs" +"?user=root&password=");

s = connect.createStatement();


String sql = "SELECT * FROM  member ORDER BY Mem_id ASC";


ResultSet rec = s.executeQuery(sql);

int row = 0;

while((rec!=null) && (rec.next()))

{ 
    
    model.addRow(new Object[0]);
    


model.setValueAt(rec.getString("Mem_id"), row, 0);

model.setValueAt(rec.getString("Mem_name"), row, 1);

model.setValueAt(rec.getString("Mem_addr"), row, 2);

model.setValueAt(rec.getString("Mem_tel"), row, 3);

row++;


}
rec.close();

} catch (Exception e) {

// TODO Auto-generated catch block

JOptionPane.showMessageDialog(null, e.getMessage());

e.printStackTrace();

}


try {

if(s != null) {

s.close();

connect.close();

}

} catch (SQLException e) {

// TODO Auto-generated catch block

e.printStackTrace();

}
}
    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     
try {

Class.forName("com.mysql.jdbc.Driver");

String jdbc = "jdbc:mysql://localhost:3306/rs?user=root&;password=";

String jdbcutf8 = "&useUnicode=true&characterEncoding=UTF-8";

connect = DriverManager.getConnection(jdbc+jdbcutf8);

s = connect.createStatement();
 
// SQL Insert
Member mb = new Member();

mb.setMemname(tf2.getText());
mb.setaddr(tf3.getText());
mb.settel(tf4.getText());


String sql = "INSERT INTO member "+ "(Mem_name,Mem_addr,Mem_tel)"+ "VALUES ('"+ Member.getMemname() + "','"+ Member.getaddr() + "','"+ Member.gettel() + "') ";

s.execute(sql);


// Reset Text Fields

tf1.setText("");

tf2.setText("");

tf3.setText("");

tf4.setText("");


JOptionPane.showMessageDialog(null,

"Record Inserted Successfully");


} catch (Exception e) {
// TODO Auto-generated catch block

JOptionPane.showMessageDialog(null, e.getMessage());

e.printStackTrace();

}

try {

if (s != null) {

s.close();

connect.close();

}

} catch (SQLException e) {

// TODO Auto-generated catch block

System.out.println(e.getMessage());

e.printStackTrace();

}
reload();
    }//GEN-LAST:event_addActionPerformed

    private void tbVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tbVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbVetoableChange

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
     try {

Class.forName("com.mysql.jdbc.Driver");


connect =  DriverManager.getConnection("jdbc:mysql://localhost:3306/rs" +"?user=root&password=");

s = connect.createStatement();

int index = tb.getSelectedRow();

String sql3 = "SELECT * FROM  member WHERE Mem_id = '"+tb.getValueAt(index, 0)+"'";
ResultSet rec = s.executeQuery(sql3);


while(rec.next()){
tf1.setText(rec.getString("Mem_id"));
tf2.setText(rec.getString("Mem_name"));
tf3.setText(rec.getString("Mem_addr"));
tf4.setText(rec.getString("Mem_tel"));
}


} catch (Exception e) {

// TODO Auto-generated catch block

JOptionPane.showMessageDialog(null, e.getMessage());

e.printStackTrace();

}

try {

if(s != null) {

s.close();

connect.close();

}

} catch (SQLException e) {

// TODO Auto-generated catch block

e.printStackTrace();

}
    
    }//GEN-LAST:event_tbMouseClicked

    private void deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deActionPerformed
       
        int index = tb.getSelectedRow();

if (index < 0) {

JOptionPane.showMessageDialog(null,

"Please select record for Delete!");

} else {

String stdid = tb.getValueAt(index, 0).toString();

Object[] options = { "Yes", "No" };

int n = JOptionPane.showOptionDialog(null,"Do you want to Delete data?","Confirm to Delete?",
        JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE, null, options,options[1]);

if (n == 0) // Confirm Delete = Yes

{
    
    
    try {

Class.forName("com.mysql.jdbc.Driver");

connect = DriverManager.getConnection("jdbc:mysql://localhost/rs"+ "?user=root&password=");

s = connect.createStatement();

String sql = "DELETE FROM member WHERE Mem_id = '"+stdid+"'";

s.execute(sql);

JOptionPane.showMessageDialog(null, "Delete Data Successfully");


} catch (Exception e) {

// TODO Auto-generated catch block

JOptionPane.showMessageDialog(null, e.getMessage());

e.printStackTrace();

}

 
try {

if (s != null) {

s.close();

connect.close();
}

} catch (SQLException e) {

// TODO Auto-generated catch block

System.out.println(e.getMessage());

e.printStackTrace();

}
//DeleteData(CustomerID); // Delete Data
reload();
// Reset Text Fields

tf1.setText("");

tf2.setText("");

tf3.setText("");

tf4.setText("");

//PopulateData(); // Reload Table

}

}


    }//GEN-LAST:event_deActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
tf1.setText("");

tf2.setText("");

tf3.setText("");

tf4.setText("");

reload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
        try {

Class.forName("com.mysql.jdbc.Driver");

connect =  DriverManager.getConnection("jdbc:mysql://localhost/rs" +"?user=root&password=");

s = connect.createStatement();

int index = tb.getSelectedRow(); 

String sql = "UPDATE member " +"SET  Mem_name = '" + tf2.getText() + "' " +", Mem_addr = '" + tf3.getText() + "' " +", Mem_tel = '" + tf4.getText() + "' WHERE Mem_id = '"+tb.getValueAt(index, 0)+"'";

s.execute(sql);

 

JOptionPane.showMessageDialog(null, "Record Update Successfully");

 

} catch (Exception e) {

// TODO Auto-generated catch block

JOptionPane.showMessageDialog(null, e.getMessage());

e.printStackTrace();

}

 

try {

if(s != null) {

s.close();

connect.close();

}

} catch (SQLException e) {

// TODO Auto-generated catch block

System.out.println(e.getMessage());

e.printStackTrace();

}

reload();

// Reset Text Fields



 


    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf1MouseClicked
   int index = tb.getSelectedRow();
        if(index<0){
        JOptionPane.showMessageDialog(null, "รหัสสมาชิกเพิ่มอัตโมมัติ");
        }else{
        
        JOptionPane.showMessageDialog(null, "รหัสสมาชิกไม่สามารถแก้ไขได้");
        }
    }//GEN-LAST:event_tf1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton de;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
